### PR TITLE
Replace recursion with a while loop

### LINKED ISSUE #8: ❌ ERROR: MAXIMUM CALL STACK SIZE EXCEEDED
Anyway to calculate the total footprint of entire smart contract?
Tried looking up $shib token contract to see how much approximate carbon usage but threw this error

### PR DESCRIPTION
**Pull request by ldeso**
Closes #8.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -92,24 +92,21 @@ const fetchTransactions = async (
...
+  do {
+    transactions = await fetchTransactions(options);
+    if (transactions.length > 0) {
+      const lastTransaction = transactions[transactions.length - 1];
+      const lastBlockNumber = Number(lastTransaction.blockNumber);
+      const selectedTransactions = transactions.filter(
+        (transaction) => Number(transaction.blockNumber) < lastBlockNumber
+      );
+      allTransactions.push(...selectedTransactions);
+      options.startBlock = lastBlockNumber;
```
Comment (ldeso) [inline src/index.ts:107]: Not sure if making a copy of the `options` object passed to getTransactions() would be better than directly modifying it.

Comment (brendanmc6) [reply src/index.ts:107]: yeah we don't want to modify fn parameters. I'll fix this up in a follow-up PR as im trying to add a loading indicator!

**Review by brendanmc6 — APPROVED** [review]
